// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOWED_ORIGIN: "https://edgeshift.tech";
	SENDER_EMAIL: "newsletter@mail.edgeshift.tech";
	SENDER_NAME: "EdgeShift Newsletter";
	SITE_URL: "https://edgeshift.tech";
	DB: D1Database;
}
