// Generated by Wrangler by running `wrangler types`

interface Env {
	RATE_LIMIT_KV: KVNamespace;
	ALLOWED_ORIGIN: string;
	SENDER_EMAIL: string;
	SENDER_NAME: string;
	SITE_URL: string;
	RESEND_API_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	ADMIN_API_KEY: string;
	RESEND_WEBHOOK_SECRET: string;
	DB: D1Database;
}
